### ISSUE TITLE
Service floods the log file in case of connectivity issues

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl.Monitoring#77]
In case of storage connectivity issues it floods the log file with exceptions added below. In case of connectivity issues the service should add delays, preferably some form of exponential backof routine.

Eventually, the service stops but in the log file no mention at all why the service stopped. 

```
2017-11-17 20:52:04.0735|5|Warn|NServiceBus.Transport.SQLServer.ExpiredMessagesPurger|Checking indexes on table [dbo].[SC.Monitoring.Ramon] failed. Exception: System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'NT AUTHORITY\LOCAL SERVICE'.
```

**Comment by mikeminutillo** [comment]
@ramonsmits this is just native NSB with the SQL Transport configured. The Monitoring code is just waiting for NSB messages to arrive.

**Comment by ramonsmits** [comment]
@mikeminutillo This should be an issue in the SQL transport repo then? @Particular/sqlserver-transport-maintainers

**Comment by mikeminutillo** [comment]
@ramonsmits yes. That was my thinking.

**Comment by MarcinHoppe** [comment]
We have a similar [issue](https://github.com/Particular/NServiceBus.SqlServer/issues/411) already.

**Comment by SzymonPobiega** [comment]
As much as I would like to address that issue in SQL transport, I'd rather wait for maintainer groups responsibility clarification before.

In the meantime, this problem can be addressed on the SC.Monitoring level by overriding the critical action and killing the endpoint (FailFast).

**Comment by mikeminutillo** [comment]
We already do

https://github.com/Particular/ServiceControl.Monitoring/blob/develop/src/ServiceControl.Monitoring/EndpointFactory.cs#L57

The fact that this is logged as a warning seems to indicate that it wouldn't fire the Critical Error action unless it happens to be sitting on a circuitbreaker that triggers Critical Error.

**Comment by SzymonPobiega** [comment]
Then I am not sure where the actual problem is. There is a circuit breaker in SQL Server transport and it is triggered. The fact that there is no information about actual cause of crash in the logs might be related to not flushing the logs properly?

**Comment by ramonsmits** [comment]
@SzymonPobiega Critical error eventually makes sure that service is shut down but that takes a long time and in that time the log is filling up very fast.

**Comment by SzymonPobiega** [comment]
In the real case, when the problem is with the connectivity rather than
auth, I think there would be natural delay caused by TCP timeouts etc.

That said, I believe we should fix it in SQL transport at some point. Just
not sure which process to use.

**Comment by ramonsmits** [comment]
This issue is still present. Service keeps running while transport is unavailable and flooding the log file.
